const SECTIONS = [
  {
    title: "1. Acceptance of terms",
    body: `By accessing or using Visibility Studio (the "Service"), you agree to be bound by these Terms & Conditions. If you do not agree, do not use the Service.`,
  },
  {
    title: "2. Description of service",
    body: `Visibility Studio audits publicly available information about local businesses — website content, contact details, and related signals — to generate visibility scores, findings, and draft outreach for the account holder's own use. The Service does not send outreach or book appointments on your behalf; those actions remain manual, human steps you take yourself.`,
  },
  {
    title: "3. Accounts and access",
    body: `You are responsible for maintaining the confidentiality of any credentials used to access the Service and for all activity under your account.`,
  },
  {
    title: "4. Acceptable use",
    body: `You agree not to use the Service to harass, defraud, or spam any business or individual, and to comply with applicable anti-spam, data-protection, and consumer-protection law in how you use any data or draft the Service produces.`,
  },
  {
    title: "5. Data accuracy",
    body: `The Service is designed to avoid fabricating facts and to cite sources for what it finds, but audit results, contact information, and scores are provided "as is" and should be independently verified before you rely on them for outreach or business decisions.`,
  },
  {
    title: "6. Intellectual property",
    body: `Redesign concepts generated by the Service are original works produced for your use and are not copies of the audited business's real site. You are responsible for how you use or represent them to third parties.`,
  },
  {
    title: "7. Disclaimer of warranties",
    body: `The Service is provided "as is" and "as available," without warranties of any kind, express or implied, including fitness for a particular purpose or non-infringement.`,
  },
  {
    title: "8. Limitation of liability",
    body: `To the maximum extent permitted by law, [Your Company Legal Name] will not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.`,
  },
  {
    title: "9. Changes to these terms",
    body: `These terms may be updated from time to time. Continued use of the Service after a change constitutes acceptance of the revised terms.`,
  },
  {
    title: "10. Contact",
    body: `Questions about these terms can be sent to [your-contact-email@example.com].`,
  },
];

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-20">
      <h1 className="text-3xl font-bold text-slate-100">Terms &amp; Conditions</h1>
      <div className="mt-4 text-xs text-amber-400/90 bg-amber-500/10 border border-amber-500/30 rounded-lg px-4 py-3">
        Template draft — replace the bracketed placeholders with your real
        company details and have this reviewed by a lawyer before treating it
        as your live terms.
      </div>
      <p className="mt-6 text-sm text-slate-500">Last updated: [date]</p>

      <div className="mt-8 space-y-8">
        {SECTIONS.map((s) => (
          <div key={s.title}>
            <h2 className="font-semibold text-slate-100">{s.title}</h2>
            <p className="text-sm text-slate-400 mt-2 leading-relaxed">{s.body}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
